import { Inter } from "next/font/google";
import "./globals.css";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Header } from "@/components/shared/Header/Header";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cifrados - Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Header />
        <Box component='main' mt={10} maxWidth={'900px'} mx={'auto'} height={'90vh'}>
          {children}
        </Box>
      </body>
    </html>
  );
}
